In [133]:
import pandas as pd
import numpy as np

In [134]:
train = pd.read_csv('../data/train1_nofilter.csv',index_col=0)
engine_split = pd.read_csv('../data/split/engine_split.csv',index_col=0)

In [135]:
stream_20 = train.merge(engine_split[engine_split["role"] == "replay"], on="engine_id")

In [136]:
engine_col = stream_20['engine_id'].unique()

In [137]:
stream_20['engine_id'].unique()

array([ 8,  9, 13, 18, 37, 46, 48, 50, 55, 62, 64, 69, 72, 74, 76, 84, 85,
       87, 90, 95])

In [138]:
stream_20.groupby('engine_id')['cycle'].max().to_list()

[150,
 201,
 163,
 195,
 170,
 256,
 231,
 198,
 193,
 180,
 283,
 362,
 213,
 166,
 210,
 267,
 188,
 178,
 154,
 283]

In [139]:
dic = {}
for x in stream_20['engine_id'].unique():
    dic[x] = stream_20[stream_20['engine_id']==x].sort_values('cycle').reset_index(drop=True)

In [140]:
engine_col = stream_20['engine_id'].unique()
cursor = 0
buffer = dic[engine_col[0]].iloc[cursor:cursor+3]

In [141]:
buffer

,engine_id,cycle,op1,op2,op3,s2,s3,s4,s7,s8,...,s12,s13,s14,s15,s17,s20,s21,RUL,role,fold
0,8,1,-0.0026,-0.0003,100.0,643.18,1585.17,1409.75,552.31,2388.12,...,521.23,2388.13,8123.47,8.4808,393,38.90,23.3468,149,replay,NaN
1,8,2,-0.0012,-0.0003,100.0,642.92,1585.97,1410.81,552.74,2388.11,...,521.82,2388.13,8120.18,8.4209,392,38.90,23.2926,148,replay,NaN
2,8,3,0.0001,0.0002,100.0,642.74,1591.11,1403.29,552.79,2388.11,...,521.52,2388.12,8122.29,8.4497,393,38.88,23.1812,147,replay,NaN

In [ ]:
def max_run_length(values):
    # 1차원 값 배열에서 같은 값이 연속으로 나온 최대 길이.
    max_len = 0
    max_val = 0
    count = 1
    for i in range(len(values)-1):
        if values[i]==values[i+1]:
            count+=1
            if max_len < count:
                max_val = values[i]
                max_len = count
        else:
            count = 1
    
    return max_len

In [128]:
max_run_length(a)

0 0 0
1 0 0
같으므로 2
현재 max보다 count가 크므로 max 교체 :  2
2 3 2
3 3 2
4 3 2
같으므로 2
5 3 2
6 3 2
같으므로 2
7 3 2
8 3 2
9 3 2
같으므로 2
10 3 2
같으므로 3
현재 max보다 count가 크므로 max 교체 :  3
11 6 3

3

In [99]:
stream_20.groupby('engine_id')['s2'].apply(lambda x:max_run_length(x.tolist()))

engine_id
8      4
9      5
13     5
18     4
37     4
46     7
48     8
50     5
55     5
62     5
64     8
69    10
72     8
74     4
76     6
84     9
85     6
87     6
90     5
95     6
Name: s2, dtype: int64

In [130]:
stream_20

,engine_id,cycle,op1,op2,op3,s2,s3,s4,s7,s8,...,s12,s13,s14,s15,s17,s20,s21,RUL,role,fold
0,8,1,-0.0026,-0.0003,100.0,643.18,1585.17,1409.75,552.31,2388.12,...,521.23,2388.13,8123.47,8.4808,393,38.90,23.3468,149,replay,NaN
1,8,2,-0.0012,-0.0003,100.0,642.92,1585.97,1410.81,552.74,2388.11,...,521.82,2388.13,8120.18,8.4209,392,38.90,23.2926,148,replay,NaN
2,8,3,0.0001,0.0002,100.0,642.74,1591.11,1403.29,552.79,2388.11,...,521.52,2388.12,8122.29,8.4497,393,38.88,23.1812,147,replay,NaN
3,8,4,-0.0021,0.0005,100.0,642.76,1592.22,1406.11,552.13,2388.14,...,521.25,2388.12,8123.80,8.4405,393,38.86,23.2371,146,replay,NaN
4,8,5,-0.0044,0.0003,100.0,643.13,1596.11,1409.34,553.61,2388.13,...,521.50,2388.15,8118.15,8.4029,392,38.88,23.2975,145,replay,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4236,95,279,-0.0008,0.0000,100.0,643.57,1603.69,1435.36,551.09,2388.16,...,520.10,2388.19,8179.43,8.5180,395,38.46,23.1727,4,replay,NaN
4237,95,280,-0.0011,-0.0004,100.0,643.46,1604.45,1433.15,551.13,2388.13,...,520.27,2388.23,8189.10,8.5225,396,38.44,23.1157,3,replay,NaN
4238,95,281,0.0026,0.0001,100.0,644.21,1595.63,1430.88,552.64,2388.19,...,519.91,2388.21,8187.88,8.5007,395,38.65,23.1434,2,replay,NaN
4239,95,282,-0.0007,-0.0004,100.0,643.65,1609.32,1422.01,551.18,2388.13,...,520.54,2388.16,8191.18,8.5332,395,38.45,23.0771,1,replay,NaN
4240,95,283,0.0019,0.0003,100.0,643.43,1609.16,1430.97,551.48,2388.21,...,519.27,2388.20,8183.58,8.5648,396,38.37,23.1041,0,replay,NaN

In [152]:
buffer = {eid:[dic[engine_col[0]].iloc[0]] for eid in range(5)}
buffer[0].append(dic[engine_col[0]].iloc[1])

In [153]:
buffer[0]

[engine_id          8
 cycle              1
 op1          -0.0026
 op2          -0.0003
 op3            100.0
 s2            643.18
 s3           1585.17
 s4           1409.75
 s7            552.31
 s8           2388.12
 s9           9048.66
 s11             47.3
 s12           521.23
 s13          2388.13
 s14          8123.47
 s15           8.4808
 s17              393
 s20             38.9
 s21          23.3468
 RUL              149
 role          replay
 fold             NaN
 Name: 0, dtype: object,
 engine_id          8
 cycle              2
 op1          -0.0012
 op2          -0.0003
 op3            100.0
 s2            642.92
 s3           1585.97
 s4           1410.81
 s7            552.74
 s8           2388.11
 s9           9040.66
 s11            47.62
 s12           521.82
 s13          2388.13
 s14          8120.18
 s15           8.4209
 s17              392
 s20             38.9
 s21          23.2926
 RUL              148
 role          replay
 fold             NaN
 Name: 1, dtype: object]

In [158]:
buffer[0][0]

engine_id          8
cycle              1
op1          -0.0026
op2          -0.0003
op3            100.0
s2            643.18
s3           1585.17
s4           1409.75
s7            552.31
s8           2388.12
s9           9048.66
s11             47.3
s12           521.23
s13          2388.13
s14          8123.47
s15           8.4808
s17              393
s20             38.9
s21          23.3468
RUL              149
role          replay
fold             NaN
Name: 0, dtype: object

In [ ]:
pd.DataFrame)

            0
1
 8        NaN
 2        NaN
-0.0012   NaN
-0.0003   NaN
 100.0    NaN
 642.92   NaN
 1585.97  NaN
 1410.81  NaN
 552.74   NaN
 2388.11  NaN
 9040.66  NaN
 47.62    NaN
 521.82   NaN
 2388.13  NaN
 8120.18  NaN
 8.4209   NaN
 392      NaN
 38.9     NaN
 23.2926  NaN
 148      NaN
 replay   NaN
 NaN      NaN

In [165]:
result = {1:10,2:10,4:14,5:20}

In [174]:
for k, v in zip(result.keys(),result.values()):
    print(k,v)

1 10
2 10
4 14
5 20